name: Continuous Integration (CI)
run-name: ${{ github.sha }}
on:
  push:
    paths:
      - "**.ts"
      - "**.js"
      - "**.tsx"
      - "**.jsx"
      - "**.astro"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Run Lint checks
        run: npm run prettier:check
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Start up dev server and run Cypress test suite
        run: npm run dev & npm run test
