name: Continuous Integration (CI)
run-name: ${{ github.sha }}
on:
  push:
    paths:
      - "**.ts"
      - "**.js"
      - "**.tsx"
      - "**.jsx"
jobs:
  cypress-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Run Lint checks
        run: npm run prettier:check
      - name: Start up dev server and run test suite
        run: npm run dev & npm run test
